String index()
{
String page = "<!DOCTYPE html>";
page += "<!--  Made by Code X Make -->";
page += "<html>";
page += "<head>";
page += "    <meta charset='utf-8'>";
page += "    <title>Porte Automatique</title>";
//page += "    <meta http-equiv='refresh' content='60'>";
page += "      <link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>";
page += "    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'>";
page += "      <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>";
page += "    <!--FAVICON-->";
page += "    <link rel='icon' type='image/png' sizes='16x16' href='http://codexmake.free.fr/favicon-16x16.png'>";
page += "</head>";
page += "  <body>";
page += "    <!--Haut de la page (bleu)-->";
page += "    <div class='w3-blue w3-xxxlarge w3-center w3-padding-16'>";
page += "      <b>Hey, <br> bienvenue !</b>";
page += "      <h4 class='w3-xlarge w3-text-black'>Ici tu peux gérer ta porte auto.</h4>";
page += "    </div>";
page += "    <br>";
page += "    <div class='w3-center'>";
page += "    <h1>"; page += currentTime[0]; page += ":"; page += minuteExtraZero; page += currentTime[1]; page += " - "; page += currentTime[2]; page += " "; page += monthList[currentTime[3]]; page += " "; page += currentTime[4]; page += interfaceErreur; page += "</h1>";
page += "    </div>";
page += "    <br>";
page += "    <!--LOG = state/mode/minuteur-->";
page += "      <table class='w3-table w3-centered w3-xlarge w3-section'>";
page += "        <tr>";
page += "        <th class='w3-dark-grey'><h1><b>État de la porte</b></h1></th>";
page += "        <th class='w3-dark-grey'><h1><b>Mode</b></h1></th>";
page += "        <th class='w3-dark-grey'><h1><b>Minuteur</b></h1></th>";
page += "          </tr>";
page += "          <tr>";
page += "        <td class='w3-white w3-border' style='width:33%; vertical-align:middle;'><h2>"; page += interface_etat_porte[etat_porte]; page += "</h2></td>";
page += "        <td class='w3-white w3-border' style='width:33%; vertical-align:middle;'><h2>"; page += interface_mode[mode_porte]; page += "</h2></td>";
page += "        <td class='w3-white w3-border' style='width:33%; vertical-align:middle;'><h2>"; page += interfaceMinuterie; page += "</h2></td>";
page += "      </tr>";
page += "    </table>";
page += "    <br>";
page += "    <div class='w3-center'>";
page += "      <!--Bouton domoticz -->";
page += "      <form action='http://";page += host;page += ":8080/#/Dashboard'><button class='w3-btn w3-blue w3-xlarge w3-padding-large w3-section w3-border' style='width:50%; border-color: black;' type='submit'>Aller sur Domoticz</button></form>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <!--Contrôle manuel de la porte -->";
page += "      <table class='w3-table w3-centered w3-xlarge w3-section'>";
page += "      <tr>";
page += "        <h1 class='w3-dark-grey w3-padding-16'><b>Contrôle manuel de la porte</b></h1>";
page += "      </tr>";
page += "      <!--BOUTON SERVO ENGAGEMENT ET BOUTON OUVRIR ETT FEMER LA PORTE -->";
page += "      <tr class='w3-white w3-center'>";
page += "     <br>";
page += "      <form class='w3-center w3-border-0 w3-container ' action='/servo' method='POST'><button class='w3-btn w3-";page +=color_servo[servo] ;page +=" w3-xxlarge w3-padding-large w3-section w3-border' style='width:50%; border-radius: 10px;' type='button submit' name='servo' value='";page +=value_servo[servo] ;page += "'> Servo : ";page +=interface_servo[servo] ;page += " </button></form>";     
page += "      <form class='w3-center w3-border-0 w3-container ' action='/action-porte-ouvrir-et-fermer' method='POST'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:94.5%;' type='button submit' name='action-porte-ouvrir-et-fermer' value='1'>Ouvrir et Fermer la porte</button></form>";
page += "      </tr>";
page += "      <!--2 bouton Haut : OUVRIR OU FERMER -->";
page += "      <tr class='w3-white w3-center'>";
page += "        <td style='width:45%;'><form class='w3-center w3-border-0 w3-container ' action='/action-porte' method='POST'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:100%;' type='button submit' name='action-porte' value='1'>Ouvrir</button></form></td>";
page += "        <td style='width:45%;'><form class='w3-center w3-border-0 w3-container ' action='/action-porte' method='POST'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:100%;' type='button submit' name='action-porte' value='0'>Fermer</button></form></td>";
page += "      </tr>";
page += "      <!--2 BOUTON OUVRIR OU FERMER : PEU-->";
page += "      <tr class='w3-white w3-center w3-border-bottom'>";
page += "        <td style='width:45%;'><form class='w3-center w3-border-0 w3-container ' action='/action-porte-peu' method='POST'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:100%;' type='button submit' name='action-porte-peu' value='1'>Ouvrir un peu </button></form></td>";
page += "        <td style='width:45%;'><form class='w3-center w3-border-0 w3-container ' action='/action-porte-peu' method='POST'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:100%;' type='button submit' name='action-porte-peu' value='0'>Fermer un peu </button></form></td>";
page += "      </tr>";
page += "      </table>";
page += "    </div>";
page += "    <br>";
page += "    <br>";
page += "    <br>";
page += "    <br>";
page += "    <div class='w3-table w3-center'>";
page += "      <h1 class='w3-dark-grey w3-padding-16'><b>Réglages <i class='material-icons' style='font-size:30px; vertical-align:middle;'>settings</i></b></h1>";
page += "      <br>";
page += "      <h1><b>Mode :</b></h1>";
page += "    </div>";
page += "    <form class='w3-container' action='/timer-settings' method='POST'>";
page += "      <div class='w3-container w3-center'>";
page += "        <select class='w3-select w3-center' style='width: 50%; font-size:20px;'name='mode'>";
page += "          <option value='"; page+=interface_mode[mode_porte]; page+="'>Choisis ton mode :</option>";
page += "          <option value='Automatique'>Automatique</option>";
page += "          <option value='Nocturne'>Nocturne (lumière automatique)</option>";
page += "          <option value='Veille'>Veille</option>";
page += "        </select> ";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <div class='w3-border-bottom'></div>";
page += "      <br>";
page += "      <h1><b>Luminositée :</b></h1>";
page += "      <h3 class='w3-xlarge w3-text-black'>Saisis le pourcentage de luminosité souhaitée : </h3>";
page += "      <br>";
page += "      <div class='w3-center'>";
page += "         <div class='w3-col s6'>";
page += "             <input type='number' id='luminosité_av' name='luminosité_av' min='1' max='100' style='width: 90%; font-size:20px;'>";
page += "             <h5 class='w3-xlarge w3-text-black'>Pour les leds RGB à l'avant de la porte</h5>";
page += "          </div>";
page += "          <div class='w3-col s6'>";
page += "             <input type='number' id='luminosité_ar' name='luminosité_ar' min='1' max='100' style='width: 90%; font-size:20px;'>";
page += "             <h5 class='w3-xlarge w3-text-black'>Pour les leds RGB à l'arrière de la porte</h5>";
page += "          </div>";
page += "      </div>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <div class='w3-border-bottom'></div>";
page += "      <br>";
page += "      <div class='w3-center'>";
page += "        <h1><b>Minuteur :</b></h1>";
page += "      </div>";
page += "      <br>";
page += "      <td class='w3-white w3-border-right w3-border-top w3-xxlarge' style='width:70%; vertical-align:middle;'>";
page += "        <div class='w3-col s6'>";
page += "          <select class='w3-select w3-center' style='font-size:20px;' name='timer-open'>";
page += "            <option value='"; page+= minuterieOuverture; page+="'>Ouverture:</option>";
page += "            <option value='désactiver'>Désactiver</option>";
page += "            <option value='00'>00H00</option>";
page += "            <option value='01'>01H00</option>";
page += "            <option value='02'>02H00</option>";
page += "            <option value='03'>03H00</option>";
page += "            <option value='04'>04H00</option>";
page += "            <option value='05'>05H00</option>";
page += "            <option value='06'>06H00</option>";
page += "            <option value='07'>07H00</option>";
page += "            <option value='08'>08h00</option>";
page += "            <option value='09'>09h00</option>";
page += "            <option value='10'>10H00</option>";
page += "            <option value='11'>11H00</option>";
page += "            <option value='12'>12H00</option>";
page += "            <option value='13'>13H00</option>";
page += "            <option value='14'>14H00</option>";
page += "            <option value='15'>15H00</option>";
page += "            <option value='16'>16H00</option>";
page += "            <option value='17'>17H00</option>";
page += "            <option value='18'>18H00</option>";
page += "            <option value='19'>19H00</option>";
page += "            <option value='20'>20H00</option>";
page += "            <option value='21'>21H00</option>";
page += "            <option value='22'>22H00</option>";
page += "            <option value='23'>23H00</option>";
page += "          </select>";
page += "        </div>";
page += "        <div class='w3-col s6'>";
page += "          <select class='w3-select w3-center' style='font-size:20px;' name='timer-close'>";
page += "            <option value='"; page+= minuterieFermeture; page+="'>Fermeture :</option>";
page += "            <option value='désactiver'>Désactiver</option>";
page += "            <option value='00'>00H00</option>";
page += "            <option value='01'>01H00</option>";
page += "            <option value='02'>02H00</option>";
page += "            <option value='03'>03H00</option>";
page += "            <option value='04'>04H00</option>";
page += "            <option value='05'>05H00</option>";
page += "            <option value='06'>06H00</option>";
page += "            <option value='07'>07H00</option>";
page += "            <option value='08'>08h00</option>";
page += "            <option value='09'>09h00</option>";
page += "            <option value='10'>10H00</option>";
page += "            <option value='11'>11H00</option>";
page += "            <option value='12'>12H00</option>";
page += "            <option value='13'>13H00</option>";
page += "            <option value='14'>14H00</option>";
page += "            <option value='15'>15H00</option>";
page += "            <option value='16'>16H00</option>";
page += "            <option value='17'>17H00</option>";
page += "            <option value='18'>18H00</option>";
page += "            <option value='19'>19H00</option>";
page += "            <option value='20'>20H00</option>";
page += "            <option value='21'>21H00</option>";
page += "            <option value='22'>22H00</option>";
page += "            <option value='23'>23H00</option>";
page += "          </select>";
page += "        </div>";      
page += "      </td>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <div class='w3-border-bottom'></div>";
page += "      <br>";
page += "      <br>";
page += "      <br>";
page += "      <!--  Bouton Confirmer ! -->";
page += "      <div class='w3-container w3-center'>";
page += "        <button class='w3-btn w3-white w3-ripple w3-mobile w3-xlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:30%;' type='button submit' name='timer-apply' ><i class='material-icons' style='font-size:40px; vertical-align:middle; color: green;'>done</i> Appliquer</button>";
page += "      </div>";
page += "    </form>";
page += "    <br>";
page += "    <br>";
page += "    <div class='footer-text'>© Copyright Code X Make 2022.</div>";
page += "    <br>";
page += "  </body>";
page += "</html>";
page += "<!--  Un énorme MERCI à Tommy Desrochers pour son excellent tutoriel sur l'esp32 et les pages web -->";
page += "<!--  Made by Code X Make  -->";
return page;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
String error404()
{
String page = "<!DOCTYPE html>";
page += "<!--  Made by Code X Make -->";
page += "<head>";
page += "  <meta charset='UTF-8'>";
page += "  <title>Error 404</title>";
page += "    <!--FAVICON-->";
page += "    <link rel='icon' type='image/png' sizes='16x16' href='http://codexmake.free.fr/favicon-16x16.png'>";
page += "<style>";
page += "@import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);";
page += "body {";
page += "  font-family: 'Open Sans';";
page += "  padding: 0;";
page += "  margin: 0;";
page += "}";
page += "#oopss {";
page += "  background: #ffffff;";
page += "  text-align: center;";
page += "  margin-bottom: 50px;";
page += "  font-weight: 400;";
page += "  font-size: 20px;";
page += "  position: fixed;";
page += "  width: 100%;";
page += "  height: 100%;";
page += "  line-height: 1.5em;";
page += "  z-index: 9999;";
page += "  left: 0px;";
page += "}";
page += "#error-text {";
page += "  top: 30%;";
page += "  position: relative;";
page += "  font-size: 40px;";
page += "}";
page += "#error-text p {";
page += "  margin: 70px 0 0 0;";
page += "}";
page += "#error-text i {";
page += "  margin-left: 10px;";
page += "}";
page += "#error-text p.hmpg {";
page += "  margin: 40px 0 0 0;";
page += "}";
page += "#error-text span {";
page += "  position: relative;";
page += "  background: #2196F3;";
page += "  color: #fff;";
page += "  font-size: 300%;";
page += "  padding: 0 20px;";
page += "  border-radius: 5px;";
page += "  font-weight: bolder;";
page += "  margin: 0 0 40px 0;";
page += "  border-top-color: #2196F3;";
page += "}";
page += "#error-text span:after {";
page += "  top: 100%;";
page += "  left: 50%;";
page += "  border: solid transparent;";
page += "  content: '';";
page += "  height: 0;";
page += "  width: 0;";
page += "  position: absolute;";
page += "  border-color: rgba(136, 183, 213, 0);";
page += "  border-top-color: #2196F3;";
page += "  border-width: 7px;";
page += "  margin-left: -7px;";
page += "}";
page += ".back {";
page += "  text-decoration: none;";
page += "  background: #5b5a5a;";
page += "  color: #fff;";
page += "  padding: 10px 20px;";
page += "  font-size: 20px;";
page += "  font-weight: 700;";
page += "  line-height: normal;";
page += "  text-transform: uppercase;";
page += "  border-radius: 3px;";
page += "}";
page += "body{ font-size: 100%; }";
page += "</style>";
page += "</head>";
page += "<body>";
page += "  <div id='oopss'>";
page += "    <div id='error-text'>";
page += "      <span>404</span>";
page += "      <p>PAGE NOT FOUND</p>";
page += "      <p class='hmpg'><a href='http://"; page+= WiFi.localIP().toString(); page+="/' class='back'>Revenir à la page d'accueil !</a></p>";
page += "    </div>";
page += "  </div>";
page += "</body>";
page += "<!--  Made by Code X Make -->";
page += "</html>";
return page;
}



String effectuer()
{
String page = "<!DOCTYPE html>";
page += "<!--  Made by Code X Make -->";
page += "<html>";
page += "<head>";
page += "    <meta charset='utf-8'>";
page += "    <title>Porte Automatique</title>";
page += "      <link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>";
page += "    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'>";
page += "      <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>";
page += "    <!--FAVICON-->";
page += "    <link rel='icon' type='image/png' sizes='16x16' href='http://codexmake.free.fr/favicon-16x16.png'>";
page += "  </head>";
page += "  <body>";
page += "    <div class='w3-blue w3-xxxlarge w3-center w3-padding-16'>";
page += "      <h1 style='font-size:110%;'><b>Te revoilà !</b></h1>";
page += "      <h4 class='w3-xlarge w3-text-black'>Je suis là pour t'aider à comprendre mes décisions !</h4>";
page += "    </div>";
page += "        <br>";
page += "        <br>";
page += "        <br>";
page += "        <div class='w3-center' style='vertical-align:middle;'>";
page += "      <h1 style='font-size:300%;'><b><i class='material-icons' style='font-size:300px; vertical-align:middle; color: green;'>task_alt</i> Opération réalisée avec succès.</b></h1>";
page += "      <br>";
page += "    </div>";
page += "        <div class='w3-container w3-center'>";
page += "            <form action='http://"; page+= WiFi.localIP().toString(); page+="/'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:60%; vertical-align:middle;' type='button submit'><i class='material-icons' style='font-size:100%; vertical-align:middle; color: black;'>home</i> Revenir à la page d'accueil !</button></form>";
page += "    </div>";
page += "</body>";
page += "</html>";
page += "<!--  Made by Code X Make  -->";
return page;
}

String echec()
{
String page = "<!DOCTYPE html>";
page += "<!--  Made by Code X Make -->";
page += "<html>";
page += "<head>";
page += "    <meta charset='utf-8'>";
page += "    <title>Porte Automatique</title>";
page += "      <link rel='stylesheet' href='https://www.w3schools.com/w3css/4/w3.css'>";
page += "    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'>";
page += "      <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>";
page += "    <!--FAVICON-->";
page += "    <link rel='icon' type='image/png' sizes='16x16' href='http://codexmake.free.fr/favicon-16x16.png'>";
page += "  </head>";
page += "  <body>";
page += "    <div class='w3-blue w3-xxxlarge w3-center w3-padding-16'>";
page += "      <h1 style='font-size:110%;'><b>Te revoilà !</b></h1>";
page += "      <h4 class='w3-xlarge w3-text-black'>Je suis là pour t'aider à comprendre mes décisions !</h4>";
page += "    </div>";
page += "        <br>";
page += "        <br>";
page += "        <br>";
page += "        <div class='w3-center' style='vertical-align:middle;'>";
page += "      <h1 style='font-size:300%;'><b><i class='material-icons' style='font-size:300px; vertical-align:middle; color: red;'>highlight_off</i> Échec de l'opération !</b></h1>";
page += "      <br>";
page += "    </div>";
page += "        <div class='w3-container w3-center'>";
page += "            <form action='http://"; page+= WiFi.localIP().toString(); page+="/'><button class='w3-btn w3-white w3-ripple w3-mobile w3-xxlarge w3-padding-large w3-section' style='border-style:solid; border-width:1px; width:60%; vertical-align:middle;' type='button submit' ><i class='material-icons' style='font-size:100%; vertical-align:middle; color: black;'>home</i> Revenir à la page d'accueil !</button></form>";
page += "        </div>";
page += "    <div class='w3-center'>";
page += "      <h4>LOG : ";page+= datalog; page+="</h4>";
page += "    </div>";
page += "</body>";
page += "</html>";
page += "<!--  Made by Code X Make  -->";
return page;
}
